sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t liam-37/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true liam-37/react-test npm test -- --coverage

after_success:
  - docker build -t liam-37/multi-client ./slient
  - docker build -t liam-37/multi-nginx ./nginx
  - docker build -t liam-37/multi-server ./server
  - docker build -t liam-37/multi-worker ./worker
